openapi: 3.0.1
info:
  title: NBA Stats API
  description: An API that retrieves NBA data & statistics, including the current scoreboard and player information.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /scoreboard:
    get:
      operationId: getScoreboard
      summary: Get today's scoreboard
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScoreboardResponse'
  /player/{player_name}:
    get:
      operationId: getPlayer
      summary: Get player information
      parameters:
        - in: path
          name: player_name
          schema:
            type: string
          required: true
          description: The full name of the player.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerResponse'

components:
  schemas:
    ScoreboardResponse:
      type: array
      items:
        type: string
    PlayerResponse:
      type: object
      properties:
        id:
          type: integer
        full_name:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        isActive:
          type: boolean
